import type { QuestionnaireStep } from './questionnaireTypes'

export const QUESTIONNAIRE_STEPS: QuestionnaireStep[] = [
  {
    id: 'travelTime',
    kind: 'choice',
    field: 'travelTime',
    indicatorLabel: 'Travel',
    title: 'When do you want to travel?',
    description: 'Start with timing so TripMora can weigh seasons, crowds, and value.',
    icon: 'calendar',
    required: true,
    options: ['Flexible', 'Next month', 'In 2-3 months', 'Spring', 'Summer', 'Autumn', 'Winter'],
  },
  {
    id: 'budget',
    kind: 'choice',
    field: 'budget',
    indicatorLabel: 'Budget',
    title: 'What budget feels right?',
    description: 'We will balance destination fit, flight distance, and comfort around this range.',
    icon: 'wallet',
    required: true,
    options: ['Shoestring', 'Budget', 'Mid-range', 'Comfortable', 'Luxury'],
  },
  {
    id: 'travelers',
    kind: 'choice',
    field: 'travelers',
    indicatorLabel: 'Group',
    title: 'Who is going?',
    description: 'The traveler mix helps shape the pace, lodging style, and suggested activities.',
    icon: 'users',
    required: true,
    options: ['Solo', 'Couple', 'Family', 'Friends'],
  },
  {
    id: 'tripStyle',
    kind: 'choice',
    field: 'tripStyle',
    indicatorLabel: 'Style',
    title: 'What kind of trip are you in the mood for?',
    description: 'Choose the energy you want TripMora to optimize around.',
    icon: 'route',
    required: true,
    options: ['Adventure', 'Balanced', 'Relaxed', 'Luxury'],
  },
  {
    id: 'visaPreference',
    kind: 'choice',
    field: 'visaPreference',
    indicatorLabel: 'Visa',
    title: 'How flexible are you on visa requirements?',
    description: 'We will avoid friction if you want simpler entry options.',
    icon: 'passport',
    required: true,
    options: [
      'Open to anywhere',
      'Prefer visa-free / on-arrival',
      'No visa needed',
      'Not sure',
    ],
  },
  {
    id: 'foodPreference',
    kind: 'choice',
    field: 'foodPreference',
    indicatorLabel: 'Food',
    title: 'Any food preferences we should respect?',
    description: 'This helps TripMora favor destinations that are easier and more enjoyable to eat in.',
    icon: 'food',
    required: true,
    options: ['No preference', 'Vegetarian', 'Vegan', 'Halal', 'Jain', 'Seafood lover'],
  },
  {
    id: 'climate',
    kind: 'choice',
    field: 'climate',
    indicatorLabel: 'Climate',
    title: 'What climate sounds best?',
    description: 'A quick temperature preference helps narrow the shortlist fast.',
    icon: 'cloud',
    required: true,
    options: ['Cool', 'Mild', 'Warm', 'Hot', 'Any'],
  },
  {
    id: 'destinationType',
    kind: 'choice',
    field: 'destinationType',
    indicatorLabel: 'Place',
    title: 'What type of destination are you drawn to?',
    description: 'Think of the backdrop you want the trip to revolve around.',
    icon: 'map',
    required: true,
    options: ['Beaches', 'Mountains', 'Cities', 'Nature', 'Mix'],
  },
  {
    id: 'withKids',
    kind: 'toggle',
    field: 'withKids',
    indicatorLabel: 'Kids',
    title: 'Travelling with kids?',
    description: 'Family-friendly logistics change the kinds of places and pacing that work best.',
    icon: 'users',
    required: true,
  },
  {
    id: 'withElderly',
    kind: 'toggle',
    field: 'withElderly',
    indicatorLabel: 'Elderly',
    title: 'Travelling with elderly companions?',
    description: 'We will lean toward easier mobility, comfort, and gentler day plans where helpful.',
    icon: 'shield',
    required: true,
  },
  {
    id: 'travelFrom',
    kind: 'text',
    field: 'travelFrom',
    indicatorLabel: 'From',
    title: 'Where are you travelling from?',
    description: 'Optional, but useful for visa context, practical flight patterns, and budget fit.',
    icon: 'plane',
    required: false,
    placeholder: 'e.g. India - helps with visa & cost',
  },
  {
    id: 'additionalNotes',
    kind: 'textarea',
    field: 'additionalNotes',
    indicatorLabel: 'Notes',
    title: 'Anything else you want TripMora to know?',
    description: 'Share constraints, interests, or little details that make the recommendations feel personal.',
    icon: 'sparkles',
    required: false,
    placeholder: 'e.g. Love diving, avoid long flights',
  },
]
